---
- name: Delete content & directory
  when: ansible_distribution == "Debian"
  file:
    state: absent
    path: /var/www/html

- name: Create project folder
  when: ansible_distribution == "Debian"
  file:
    path: /var/www/html
    state: directory
- name: Pull Localhost Application via Git
  when: ansible_distribution == "Debian"
  ansible.builtin.git:
    repo: https://github.com/ilekicgrid/Php-CRUD-app-for-ansible.git
    dest: /var/www/html/
    version: master